In [18]:
import numpy as np
from scipy import stats

In [19]:
rolls = np.random.choice([1,2,3,4,5,6],10000)
rolls

array([5, 3, 3, ..., 1, 5, 2])

In [20]:
rolls.mean()

3.4995

In [34]:
n = 15

rolls = np.random.choice([1,2,3,4,5,6],n)
rolls

array([4, 3, 2, 5, 3, 5, 1, 2, 4, 2, 1, 5, 3, 6, 4])

In [35]:
rolls.mean()

3.3333333333333335

In [27]:
import math

In [32]:
t = (rolls.mean()) - 3.5 / (rolls.std() / math.sqrt(n))
t

-5.462121243569207

In [31]:
stats.t(n-1).cdf(t) * 2

8.372076992351839e-05

###### fictional universe where they are confused and they think the average die roll is 4.5 aka H0 = 4.5

In [64]:
np.random.seed(15)
n = 15

rolls = np.random.choice([1,2,3,4,5,6],n)
rolls

array([1, 6, 5, 6, 1, 5, 4, 4, 6, 6, 2, 6, 1, 3, 5])

In [65]:
rolls.mean()

4.066666666666666

In [66]:
rolls.std()

1.9136933459209768

In [67]:
t = (rolls.mean() - 4.5) / (rolls.std() / math.sqrt(n))
t

-0.8769914923589074

In [68]:
stats.t(n-1).cdf(t) * 2

0.39529136156632283

##### reject the null hypothesis^